hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/linkedList.o -c ./src/linkedList.cpp
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./bin/source ./src/source.cpp
	
calistir:
	./bin/source